CrowdStrike/faltest

.travis.yml, README.md, examples/runner-only/package.json, yarn.lock
=> chore: add overriding chromedriver version docs

.travis.yml, package.json, packages/remote/src/index.js
=> chore: test firefox on ci

packages/remote/package.json
not sure how it made it into deps
=> fix: move `clear-module` to dev deps

appveyor.yml, packages/remote/package.json, packages/remote/src/cp.js, packages/remote/src/index.js
https://github.com/sindresorhus/execa/issues/173
=> chore: try appveyor

packages/page-objects/src/base-page-object.js
This reverts parts of commit 0a47b075a11af9e3d5dc32c8f2f33e2481d578ac.
=> fix: allow instanceof calls through

packages/browser/package.json, packages/browser/test/acceptance/index-test.js, packages/chai/package.json, packages/chai/test/integration/index-test.js, packages/page-objects/package.json, packages/page-objects/test/acceptance/extend-test.js, packages/page-objects/test/acceptance/index-test.js, packages/page-objects/test/acceptance/purge-old-test.js, packages/page-objects/test/acceptance/set-password-test.js, packages/remote/package.json, packages/remote/test/acceptance/redact-password-test.js
simplify the dep tree when releasing
=> chore: remove dev deps

README.md
cc @NullVoxPopuli for visibility
=> chore: add real world examples

doc/page-objects.md, packages/page-objects/src/base-page-object.js, packages/page-objects/test/acceptance/chain-test.js
=> feat: add page object chaining option

doc/chai.md, examples/full-suite/tests/sample-test.js, packages/chai/index.js, packages/chai/package.json, packages/chai/test/integration/index-test.js, packages/page-objects/package.json, packages/page-objects/src/element.js, packages/page-objects/test/acceptance/api-verification-test.js
=> feat: add `isDisplayed` `waitForVisible`, `waitForHidden`

packages/remote/src/index.js, packages/remote/test/acceptance/multiple-browsers-test.js
=> fix: add test for multi browser and fix assumption

packages/lifecycle/package.json, packages/lifecycle/src/index.js, packages/lifecycle/test/acceptance/multiple-browsers-test.js
=> feat: support multiple browsers in lifecycle

README.md, examples/multiple-browsers/README.md, examples/multiple-browsers/package.json, examples/multiple-browsers/tests/sample-test.js, packages/cli/package.json, packages/cli/src/index.js, packages/lifecycle/src/index.js, packages/utils/src/defaults.js
=> feat: add multi browser support to the cli

package.json, scripts/examples.js
to allow for more combinations
=> chore: change how examples are tested

examples/full-suite/config/dev.json, examples/full-suite/config/prod.json, examples/full-suite/page-objects/login.js, examples/full-suite/tests/sample-test.js
=> chore: add a password to the full suite test

packages/mocha/src/tag.js, packages/mocha/test/acceptance/index-test.js, packages/mocha/test/fixtures/tag-test.js, packages/mocha/test/unit/tag-test.js
=> fix for tag substrings

packages/lifecycle/src/index.js, packages/lifecycle/test/unit/index/set-up-web-driver-test.js, packages/remote/src/index.js, packages/remote/test/acceptance/multiple-browsers-test.js, packages/remote/test/integration/index-test.js
BREAKING CHANGE: remote api change
startWebDriver and startBrowser now take whole options object instead of just overrides.
=> feat: allow modifying capabilities via `customizeCapabilities`

packages/cli/package.json, packages/page-objects/package.json, yarn.lock
BREAKING CHANGE: track new breaking change
=> fix: track new breaking change

packages/lifecycle/src/index.js, packages/lifecycle/test/unit/index/set-up-web-driver-test.js
=> fix: recycle state if overrides change

packages/browser/index.js, packages/browser/test/acceptance/redact-password-test.js, packages/utils/src/password.js, packages/utils/src/require-before-webdriverio.js
=> fix: redact any password in error messages

packages/page-objects/test/acceptance/elements-test.js
Closes #199
@NullVoxPopuli The problem we were encountering was inside `eachProperties`, we were using `this._create`, which is scoped to the parent selector `'.foo'`, instead of the passed in `create`, which is scoped to the array item.
=> chore: add `Elements` iterating tests

README.md, packages/browser/test/acceptance/redact-password-test.js, packages/utils/src/require-before-webdriverio.js, packages/utils/src/scope-debug.js
=> fix: webdriver logging regressed

package.json, packages/browser/package.json, packages/chai/package.json, packages/cli/package.json, packages/lifecycle/package.json, packages/mocha/package.json, packages/page-objects/package.json, packages/remote/package.json, packages/utils/package.json, yarn.lock
This reverts commit d03d8fdd7e5467466f35c23f2f3936320e3f3f3e.
#216
=> Revert "chore(deps): update dependency mocha to v7"

helpers/chai.js, package.json, packages/mocha/package.json, packages/mocha/test/acceptance/index-test.js, packages/mocha/test/fixtures/reporter-test.js, yarn.lock
=> chore: add mocha reporter regression test

package.json, packages/browser/package.json, packages/chai/package.json, packages/cli/package.json, packages/lifecycle/package.json, packages/mocha/package.json, packages/mocha/src/index.js, packages/page-objects/package.json, packages/remote/package.json, packages/utils/package.json, yarn.lock
instead of intuitive `reporterOptions`
=> fix: use documented `reporterOption`

package.json, packages/browser/package.json, packages/chai/package.json, packages/cli/package.json, packages/lifecycle/package.json, packages/mocha/package.json, packages/mocha/src/index.js, packages/page-objects/package.json, packages/remote/package.json, packages/utils/package.json, yarn.lock
https://github.com/mochajs/mocha/pull/4153
=> fix: bring back `reporterOptions`

.travis.yml, README.md, appveyor.yml
https://github.com/giggio/node-chromedriver/commit/67253e1b2bdc90e573843cd06c574e1550b6f411
=> use new `DETECT_CHROMEDRIVER_VERSION`

packages/remote/package.json, yarn.lock
because of https://github.com/webdriverio/webdriverio/issues/4996
=> fix: revert webdriverio 5.18.6

examples/full-suite/page-objects/login.js
https://github.com/webdriverio/webdriverio/pull/5109
=> chore: update `switchToFrame` call in example

packages/lifecycle/src/index.js, packages/lifecycle/test/unit/index/set-up-web-driver-test.js
=> fix: recover after login failure

README.md, examples/full-suite/helpers/mocha.js, examples/full-suite/package.json, packages/cli/src/index.js, packages/lifecycle/package.json, packages/lifecycle/src/index.js, packages/mocha/package.json, packages/mocha/src/failure-artifacts.js, packages/mocha/src/index.js, packages/mocha/test/acceptance/index-test.js, packages/mocha/test/fixtures/failure-artifacts-test.js
=> feat: add failure artifacts to tests

packages/page-objects/src/elements.js, packages/page-objects/test/acceptance/elements-test.js
=> add `Elements.getLength` and add `Elements.nth`

README.md, helpers/fs.js, package.json, scripts/precommit.js
=> feat: regenerate readme options on release

README.md, packages/cli/bin/index.js, packages/cli/package.json, packages/cli/src/index.js, packages/cli/src/worker.js, yarn.lock
=> feat: add `--duplicate` option

.travis.yml, appveyor.yml, config/ember-cli-update.json, package.json
BREAKING CHANGE: bump min node 10
=> chore: track `standard-node-template`

packages/remote/package.json, packages/remote/src/index.js, yarn.lock
=> fix: update ps-list v8

packages/mocha/src/failure-artifacts.js, packages/mocha/test/acceptance/index-test.js
=> feat: store the url in a text file for failure artifacts

packages/mocha/src/failure-artifacts.js, packages/mocha/test/acceptance/index-test.js, packages/mocha/test/fixtures/failure-artifacts-test.js
=> fix: fix failure artifacts in edge and firefox

packages/remote/test/integration/index-test.js
instead of hanging until timeout.
=> chore: reject on error

packages/cli/test/acceptance/index-test.js
=> chore: add parseJson

packages/remote/package.json, yarn.lock
https://github.com/mozilla/geckodriver/issues/2011. We can update again after updating past webdriverio 6.
=> fix: revert geckodriver

packages/browser/index.js, packages/browser/test/acceptance/index-test.js, packages/cli/test/acceptance/index-test.js, packages/remote/package.json, packages/remote/src/index.js, packages/remote/test/integration/index-test.js, yarn.lock
Inspired by https://github.com/CrowdStrike/faltest/pull/676.
=> feat!: update to webdriverio 6

packages/remote/package.json, yarn.lock
https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/
=> feat!: update to webdriverio 7

.github/workflows/ci.yml, packages/remote/src/index.js
ChromeDriver changed its startup message from "ChromeDriver was started successfully." to "ChromeDriver was started successfully on port XXXXX."
=> fix: fix chromedriver start

.github/workflows/ci.yml
This reverts commit 641abb47f87fad4862af09700b5f74125f5ce5e4.
=> Revert "chore: disable global install test"

packages/mocha/test/acceptance/index-test.js, packages/remote/test/integration/index-test.js
This reverts commit 783a9643251c1053e8d08f2e744fd535ad519474.
=> Revert "chore: skip edge test"
