CrowdStrike/faltest

- .eslintrc.js
- packages/page-objects/test/acceptance/api-verification-test.js
- packages/remote/test/acceptance/redact-password-test.js
why oh why is no-exclusive-tests set to warn?
> chore: fix mocha lint

- packages/remote/src/index.js
now that https://github.com/webdriverio/webdriverio/pull/4906 is out and it doesn't work as intended
> chore: update `connectionRetryTimeout` comment

- packages/cli/bin/index.js
needed because the browser hanging will cause mocha to stall
> fix: simulate Mocha's --exit

- packages/page-objects/src/element.js
- packages/page-objects/test/acceptance/api-verification-test.js
The `getAttribute` method in `Element` is missing a return statement.
> fix: missing return statement in getAttribute

- packages/page-objects/src/base-page-object.js
to match `_createManyUnscoped`
Closes #279
> fix: rename `_extendUnscopedMany` to `_extendManyUnscoped`

- packages/cli/bin/index.js
This is unnecessary. Consumers can do this themselves.
> fix: stop logging process.env

- examples/full-suite/helpers/mocha.js
- packages/lifecycle/src/index.js
- packages/lifecycle/test/unit/index/set-up-web-driver-test.js
- packages/mocha/src/failure-artifacts.js
- packages/mocha/src/index.js
- packages/mocha/test/fixtures/failure-artifacts-test.js
We can remove the try/catch override for every hook by using `this.currentTest.state` in `afterEach` instead.
BREAKING CHANGE: `createFailureArtifacts` was removed because it is no longer necessary.
> feat: optimize failure artifacts

- .eslintrc.js
- packages/lifecycle/src/index.js
- packages/mocha/test/acceptance/index-test.js
- packages/mocha/test/fixtures/failure-artifacts-test.js
> fix: don't create failure artifacts for `this.skip` tests

- packages/lifecycle/src/index.js
- packages/mocha/src/failure-artifacts.js
- packages/mocha/test/acceptance/index-test.js
- packages/mocha/test/fixtures/failure-artifacts-test.js
Right now, errors in `before` are not getting handled.
> fix: correctly handle failure artifacts in `before` and `after`

- examples/full-suite/helpers/mocha.js
- packages/mocha/src/flag.js
- packages/mocha/src/mocha.js
- packages/mocha/src/role.js
- packages/mocha/test/fixtures/flag-test.js
- packages/mocha/test/fixtures/role-test.js
This will prevent `this.test.file` being incorrect based on eagerly calling the real `describe`.
BREAKING CHANGE: The first param of `createRolesHelper` and `createFlaggedTest` has changed to be the object source of the mocha hooks (usually `global`).
> fix: defer accessing mocha hooks until needed

- packages/mocha/test/acceptance/index-test.js
- packages/mocha/test/fixtures/null-reporter.js
to prevent expected failures in logs confusing any real failures
> chore: use null reporter in tests

- package.json
- yarn.lock
warning " > sinon-chai@3.6.0" has incorrect peer dependency "sinon@>=4.0.0 <11.0.0".
> chore: get rid of sinon-chai warning

- packages/remote/src/index.js
An orphaned webdriver browser would only get its ppid set to 1 in mac. In linux, it would get set to systemd, which is not 1. We can't rely on that number, so instead we just kill any left over browsers spawned by webdriver, even if another theoretical webdriver instance is using them.
> fix: kill all remaining webdriver browsers

- packages/mocha/src/failure-artifacts.js
- packages/mocha/src/index.js
- packages/mocha/test/acceptance/index-test.js
- packages/mocha/test/fixtures/failure-artifacts-test.js
currently, failed artifacts are being written only when test fails. Added feature to write failed artifacts on every test retry and added retry attempt count to file names
> feat: add attempt count to failure artifacts

- packages/lifecycle/src/index.js
- packages/lifecycle/test/unit/index/set-up-web-driver-test.js
If you are using mocha-helpers that can retry lifecycle hooks, and there is a login failure, it would not retry correctly.
> fix: reset sessionError in beforeAll

- packages/remote/src/index.js
after a successful firefox connection
> fix: reset connectionRetryCount back to default

- packages/lifecycle/src/index.js
I saw in some logs the "Writing failure artifact to ..." line in the middle of a getPageSource output. I think it was the failure output of a `beforeEach` running at the same time as the failure output of an `it`. This is because failureArtifacts calls in `beforeEach` don't get awaited until `setUpWebDriverAfterEach`. If we can await the code before then next `it` happens, we may be able to prevent this.
> fix: call `waitForPromisesToFlushBetweenTests` in `setUpWebDriverBeforeEach`

- packages/mocha/src/failure-artifacts.js
- packages/mocha/src/index.js
- packages/mocha/test/acceptance/index-test.js
When using retries, if the test retries to success, it is hard to find the original test error. You have to view the logs with `DEBUG=@faltest/mocha` and look for `@faltest/mocha Retrying failed test "my test": my error`. This makes it a lot easier to diagnose a flakey error.
> feat: store original test error in failure artifact

- packages/lifecycle/src/index.js
> feat: call `waitForPromisesToFlushBetweenTests` in every lifecycle hook

- .npmignore
Newer NPM versions are ignoring all code in every package.
> fix: add `!/packages/` to .npmignore

- .github/workflows/ci.yml
```
/home/runner/work/faltest/faltest/fixtures/global-install/node_modules/cliui/build/index.cjs:293
const wrap = require('wrap-ansi');
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/faltest/faltest/fixtures/global-install/node_modules/wrap-ansi/index.js from /home/runner/work/faltest/faltest/fixtures/global-install/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/runner/work/faltest/faltest/fixtures/global-install/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (/home/runner/work/faltest/faltest/fixtures/global-install/node_modules/cliui/build/index.cjs:293:14)
at Object.<anonymous> (/home/runner/work/faltest/faltest/fixtures/global-install/node_ …
```
> chore: disable global install test

- packages/cli/src/index.js
There is a conflict with NX 17+ where --envFile was replaced with --env. This disrupted our faltest e2e tasks, so adding an "environment" alias will workaround this.
> Create alias for "env" called "environment"

- .github/workflows/ci.yml
- packages/remote/package.json
- yarn.lock
This update uses the new storage location for msedgedriver `msedgedriver.microsoft.com`. The domain `msedgedriver.azureedge.net` is deprecated and microsoft has moved the storage location for msedgedriver to `msedgedriver.microsoft.com`
Closes #872.
> fix: update `browser-webdriver-downloader` to `3.0.4`
